# Generated by Django 4.0.6 on 2024-01-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='product',
            field=models.ForeignKey(help_text='محصولی که میخواهید برایش اطلاعات تکمیلی ایجاد کنید را انتخاب کنید', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product', verbose_name='محصول'),
        ),
    ]
