# Generated by Django 4.0.6 on 2024-03-30 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان آفر')),
                ('description', models.TextField(verbose_name='توضیحات در مورد آفر')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('start_date', models.DateField(default=datetime.datetime(2024, 3, 30, 16, 30, 36, 841068, tzinfo=utc), verbose_name='زمان شروع')),
                ('end_date', models.DateField(verbose_name='زمان پایان')),
                ('products', models.ManyToManyField(related_name='offers', to='product.product', verbose_name='محصولات')),
            ],
        ),
    ]
