# Generated by Django 4.0.6 on 2024-04-01 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'آفر', 'verbose_name_plural': 'آفرها'},
        ),
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='این گزینه اگر فعال باشد آفر فعال است و در سایت نمایش داده میشود', verbose_name='وضعیت آفر'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 1, 10, 43, 48, 571655, tzinfo=utc), verbose_name='زمان شروع'),
        ),
    ]
