# Generated by Django 4.0.6 on 2024-02-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='عنوان و کد تخفیف')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='تعداد موجود')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
